export { Header } from './Header';
export { DisciplinesSection } from './DisciplinesSection';
export { GroupsSection } from './GroupsSection';
export { PersonalCabinet } from './PersonalCabinet';
export { ScheduleSection } from './ScheduleSection';
export { TeacherAttendanceSection } from './TeacherAttendanceSection';
export { TeacherPerformanceSection } from './TeacherPerformanceSection';
export { CuratorSection } from './CuratorSection';
export { CuratorGroupDetails } from './CuratorGroupDetails';
